version: '2'
services:
  app:
    build: .
    container_name: app
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://dbuser:dbpass123@postgres/desafiodev
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass123
      POSTGRES_DB: desafiodev